version: '2'
services:

  # The Application
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"

  # The nginx Server
  nginx:
    build:
      context: ./
      dockerfile: nginx.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - 80:80

  # The Database
  database:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=oppi-docker"
      - "MYSQL_USER=oppi"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=root"
    ports:
        - "33061:3306"

volumes:
  dbdata:
